import assert from "node:assert/strict";
import test from "node:test";
import { mkdir, readFile, writeFile, cp } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createServer } from "node:http";
import sharp from "sharp";
import { chromium } from "playwright";
import { fixture, key, candidateId, json } from "../helpers/finished-fixture.mjs";
import { PAGES_INDEX_SCHEMA_ID } from "../../server/pages-store.mjs";
import { candidateFileRelativePath } from "../../server/candidate-storage.mjs";
import { prepareFinishedPage } from "../../server/finished-pages.mjs";
import { defaultLetteringSettings } from "../../server/lettering-settings.mjs";
import { serveProductionAsset } from "../../server/http-support.mjs";
import { renderFinishedImage } from "../../server/finished-render.mjs";
import { createStoryCanvasServer } from "../../server/index.mjs";
import { hashCanonicalJson } from "../../server/workflow-definition.mjs";
test("正式嵌字使用浏览器共享排版，输出保持尺寸且无字时保留底图像素", async t => {
  const distRoot = fileURLToPath(new URL("../../dist/", import.meta.url));
  const server = createServer((request, response) => void serveProductionAsset(response, new URL(request.url, "http://local"), distRoot));
  await new Promise(resolve => server.listen(0, "127.0.0.1", resolve));
  t.after(() => new Promise(resolve => server.close(resolve)));
  const origin = `http://127.0.0.1:${server.address().port}`;
  const clean = await sharp({ create: { width: 512, height: 768, channels: 3, background: "#80b0a0" } }).png().toBuffer();
  const lettering = { dialogue: [], items: [], settings: defaultLetteringSettings(), canvas: "2:3" };
  const empty = await renderFinishedImage(clean, lettering, origin);
  assert.deepEqual(await sharp(empty).removeAlpha().raw().toBuffer(), await sharp(clean).raw().toBuffer());
  lettering.dialogue = [{ id: "dialogue-123456789abc", mode: "narration", text: "阳光照进房间" }, { id: "dialogue-223456789abc", mode: "heart", text: "喜欢你" }, { id: "dialogue-323456789abc", mode: "speech", speaker: "npc", text: "早上好" }];
  const image = await renderFinishedImage(clean, lettering, origin);
  const info = await sharp(image).metadata();
  assert.equal(info.width, 512); assert.equal(info.height, 768);
  assert.notEqual(hashCanonicalJson([...image]), hashCanonicalJson([...empty]));
});

test("浏览器成品导航、双版本切换、返回编辑与输出按钮可用", async t => {
  const f = await fixture(t);
  const narrativePath = path.join(f.directory, `pages/${key.page_id}.content.json`);
  const narrative = JSON.parse(await readFile(narrativePath, "utf8"));
  await json(narrativePath, { ...narrative, dialogue: [
    { id: "dialogue-123456789abc", mode: "narration", text: "阳光照进房间" },
    { id: "dialogue-223456789abc", mode: "heart", text: "喜欢你" },
    { id: "dialogue-323456789abc", mode: "speech", speaker: "npc", text: "早上好" },
  ] });
  await writeFile(f.file, await sharp({ create: { width: 1280, height: 1920, channels: 3, background: "#80b0a0" } }).png().toBuffer());
  await f.run(await f.prepare(), { upscale: source => sharp(source).resize(2560, 3840).png().toBuffer() });
  const secondKey = { ...key, page_id: "page-002" };
  for (const suffix of ["content", "prompt"]) await writeFile(path.join(f.directory, `pages/page-002.${suffix}.json`), await readFile(path.join(f.directory, `pages/${key.page_id}.${suffix}.json`)));
  await json(path.join(f.directory, "pages/index.json"), { $schema: PAGES_INDEX_SCHEMA_ID, pages: [key, secondKey].map(key => ({ page_id: key.page_id, owner_kind: "story", sequence_id: "sequence" })) });
  const secondFile = path.join(f.directory, candidateFileRelativePath(secondKey, candidateId));
  await cp(path.dirname(f.file), path.dirname(secondFile), { recursive: true });
  await f.run((await f.operations.mutateDerived("demo", () => prepareFinishedPage(f.root, "demo", f.directory, { page_key: secondKey, candidate_id: candidateId }))).value, { upscale: source => sharp(source).resize(2560, 3840).png().toBuffer() });
  const nextCandidate = "candidate-22222222-2222-4222-8222-222222222222";
  const nextFile = path.join(f.directory, candidateFileRelativePath(key, nextCandidate));
  await cp(path.dirname(f.file), path.dirname(nextFile), { recursive: true });
  await json(nextFile.replace("image.png", "result.json"), { version: 1, status: "available", page_key: key, candidate_id: nextCandidate, file: candidateFileRelativePath(key, nextCandidate), seed: 5678, task_id: "render-20260826T010203Z" });
  let releaseOutput;
  const outputGate = new Promise(resolve => { releaseOutput = resolve; });
  let rendering;
  const renderingStarted = new Promise(resolve => { rendering = resolve; });
  const running = f.run(await f.prepare(), { render: async clean => { rendering(); await outputGate; return clean; } });
  t.after(async () => { releaseOutput(); await running; });
  await renderingStarted;
  const server = await createStoryCanvasServer({ projectRoot: f.root, appRoot: fileURLToPath(new URL("../../", import.meta.url)), production: true, localConfig: { comfyui_urls: [] }, hardwareStatusReader: async () => ({ cpu: { available: false }, memory: { available: false }, gpu: { available: false }, comfyui: { connected: false, status: "offline" } }) });
  await new Promise(resolve => server.listen(0, "127.0.0.1", resolve));
  const browser = await chromium.launch(process.platform === "win32" ? { channel: "msedge", headless: true } : { headless: true });
  t.after(async () => { await browser.close(); await new Promise(resolve => server.close(resolve)); });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = []; page.on("pageerror", error => errors.push(error.message));
  await page.goto(`http://127.0.0.1:${server.address().port}/?project=demo&tab=finished`);
  try { await page.getByRole("heading", { name: "成品", exact: true }).waitFor({ timeout: 10000 }); }
  catch (error) { t.diagnostic(await page.locator("body").innerText()); t.diagnostic(JSON.stringify(errors)); throw error; }
  await page.locator(".task-status-menu summary").click();
  const activeTask = page.locator(".task-card--running");
  await activeTask.getByText(/正在嵌字/).waitFor();
  assert.equal(await activeTask.getByRole("button", { name: "暂停", exact: true }).count(), 0);
  await activeTask.locator(".task-card__open").click();
  await page.getByRole("dialog").getByText(/正在嵌字/).waitFor();
  await page.keyboard.press("Escape");
  releaseOutput(); const completed = await running;
  await page.getByRole("button", { name: "刷新成品状态", exact: true }).click();
  await page.waitForFunction(id => document.querySelector(".finished-card img")?.getAttribute("src")?.includes(id), completed.id);
  assert.match(await page.locator(".finished-card img").first().getAttribute("src"), /lettered.png(?:\?|$)/);
  assert.equal(await page.getByRole("button", { name: "查看无字版", exact: true }).count(), 0);
  assert.equal(await page.getByRole("button", { name: "重新输出", exact: true }).count(), 0);
  assert.equal(await page.locator(".finished-page-link").first().getAttribute("title"), "第一章 / 片段 / 测试页");
  await page.locator(".finished-image").first().click();
  await page.getByRole("dialog", { name: "001 嵌字版" }).waitFor();
  const variantSrc = await page.locator(".image-lightbox img").getAttribute("src");
  assert.equal(new URL(variantSrc, page.url()).search, "?w=1024", "灯箱默认加载压缩变体");
  const variantResponse = await page.request.get(new URL(variantSrc, page.url()).href);
  assert.equal(variantResponse.headers()["content-type"], "image/webp");
  await page.getByRole("button", { name: "查看原图", exact: true }).click();
  await page.getByRole("button", { name: "已显示原图", exact: true }).waitFor();
  const originalSrc = await page.locator(".image-lightbox img").getAttribute("src");
  assert.equal(new URL(originalSrc, page.url()).search, "");
  const originalResponse = await page.request.get(new URL(originalSrc, page.url()).href);
  const originalRecord = JSON.parse(await readFile(path.join(f.directory, "finished/page-001.json"), "utf8"));
  assert.deepEqual(await originalResponse.body(), await readFile(path.join(f.directory, originalRecord.outputs.lettered)), "大图接口应逐字节返回原始 PNG");
  await page.getByRole("button", { name: "已显示原图", exact: true }).click();
  await page.waitForFunction(src => document.querySelector(".image-lightbox img")?.getAttribute("src") === src, variantSrc);
  await page.getByRole("button", { name: "查看原图", exact: true }).waitFor();
  await page.locator(".image-lightbox img").evaluate(img => img.decode());
  await page.getByRole("button", { name: "原始大小（1:1）", exact: true }).click();
  await page.waitForFunction(() => {
    const img = document.querySelector(".image-lightbox img");
    return img?.getBoundingClientRect().width === img?.naturalWidth && img?.getBoundingClientRect().height === img?.naturalHeight;
  });
  assert.equal(await page.locator(".image-lightbox output").innerText(), "100%");
  await page.getByRole("button", { name: "适合窗口", exact: true }).click();
  for (const viewport of [{ width: 1440, height: 1000 }, { width: 390, height: 700 }]) {
    await page.setViewportSize(viewport);
    await page.locator(".image-lightbox img").evaluate(img => img.decode());
    const image = await page.locator(".image-lightbox img").boundingBox();
    const stage = await page.locator(".image-lightbox__media").boundingBox();
    assert.ok(image.x >= stage.x - 1 && image.y >= stage.y - 1 && image.x + image.width <= stage.x + stage.width + 1 && image.y + image.height <= stage.y + stage.height + 1, "完整大图应适合可用区域");
    assert.ok(Math.abs(image.width / image.height - 2 / 3) < 0.01);
  }
  await page.getByRole("button", { name: "下一张", exact: true }).click();
  await page.getByRole("dialog", { name: "002 嵌字版" }).waitFor();
  await page.getByRole("button", { name: "上一张", exact: true }).click();
  await page.getByRole("dialog", { name: "001 嵌字版" }).waitFor();
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.locator(".image-lightbox__media").click({ position: { x: 5, y: 5 } });
  assert.equal(await page.locator(".image-lightbox").count(), 0);
  await page.locator(".finished-image").first().click();
  await page.getByRole("button", { name: "放大图片" }).click();
  await page.keyboard.press("ArrowRight");
  await page.getByRole("dialog", { name: "002 嵌字版" }).waitFor();
  await page.waitForFunction(() => {
    const img = document.querySelector(".image-lightbox img").getBoundingClientRect();
    const stage = document.querySelector(".image-lightbox__media").getBoundingClientRect();
    return img.width <= stage.width + 1 && img.height <= stage.height + 1;
  });
  await page.keyboard.press("ArrowRight");
  assert.equal(await page.getByRole("dialog", { name: "002 嵌字版" }).count(), 1);
  await page.keyboard.press("ArrowLeft");
  await page.getByRole("dialog", { name: "001 嵌字版" }).waitFor();
  await page.keyboard.press("Escape");
  // 阅读预览使用与离线 HTML 相同的文档，水平模式接受纵向鼠标滚轮。
  await page.setViewportSize({ width: 900, height: 1000 });
  await page.getByRole("button", { name: "阅读预览", exact: true }).click();
  const readerFrame = page.frameLocator('iframe[title="成品连续阅读"]');
  await readerFrame.getByRole("button", { name: "水平", exact: true }).click();
  const reader = readerFrame.locator(".finished-reader");
  await reader.locator("img").first().evaluate(img => img.decode());
  await reader.hover();
  await page.mouse.wheel(0, 900);
  await readerFrame.getByLabel("当前页码").filter({ hasText: /^2$/ }).waitFor();
  assert.ok(await reader.evaluate(element => element.scrollLeft > 0 && element.scrollTop === 0));
  assert.equal(await reader.locator("figcaption, h1, h2").count(), 0, "阅读区仅显示图片");
  await readerFrame.getByRole("button", { name: "垂直", exact: true }).click();
  await readerFrame.getByLabel("当前页码").filter({ hasText: /^2$/ }).waitFor();
  assert.ok(await reader.evaluate(element => element.scrollTop > 0 && element.scrollLeft === 0));
  await page.keyboard.press("Escape");
  await page.getByRole("dialog", { name: "阅读预览", exact: true }).waitFor({ state: "hidden" });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.locator(".finished-card img").first().evaluate(img => img.decode());
  await mkdir(fileURLToPath(new URL("../../runtime/", import.meta.url)), { recursive: true });
  await page.screenshot({ path: fileURLToPath(new URL("../../runtime/finished-ui.png", import.meta.url)) });
  await page.locator(".finished-page-link").first().click();
  const output = page.getByRole("button", { name: "输出成品", exact: true });
  await output.waitFor();
  assert.equal(await output.isEnabled(), true);
  await page.getByRole("button", { name: "查看成品", exact: true }).click();
  await page.getByRole("dialog", { name: "当前成品", exact: true }).waitFor();
  await page.keyboard.press("Escape");
  const bounds = await output.boundingBox();
  assert.ok(bounds.y + bounds.height <= 1000, "输出按钮应在当前页面可见区域内");
  await page.getByRole("tab", { name: "嵌字", exact: true }).click();
  await page.getByLabel("旁白", { exact: true }).fill("尚未保存的旁白");
  await page.locator(".current-image__lettering-target .heart-lettering").waitFor();
  const normalizedBoxes = selector => page.locator(selector).evaluate(overlay => {
    const host = overlay.getBoundingClientRect();
    return [...overlay.querySelectorAll(".lettering-object")].map(item => {
      const rect = item.getBoundingClientRect();
      return [(rect.x - host.x) / host.width, (rect.y - host.y) / host.height, rect.width / host.width, rect.height / host.height];
    });
  });
  const expectedBoxes = await normalizedBoxes(".current-image__lettering-target .lettering-overlay");
  await page.getByTitle("点击放大查看", { exact: true }).click();
  for (const viewport of [{ width: 1440, height: 1000 }, { width: 390, height: 700 }]) {
    await page.setViewportSize(viewport);
    await page.locator(".image-lightbox__lettering .heart-lettering").waitFor();
    await page.locator(".image-lightbox__lettering").getByText("尚未保存的旁白", { exact: true }).waitFor();
    await page.getByRole("button", { name: "原始大小（1:1）", exact: true }).click();
    const boxes = await normalizedBoxes(".image-lightbox__lettering .lettering-overlay");
    assert.equal(boxes.length, expectedBoxes.length);
    boxes.forEach((box, index) => box.forEach((value, axis) => assert.ok(Math.abs(value - expectedBoxes[index][axis]) < 0.005, "大图文案相对位置与编辑预览一致")));
    const image = await page.locator(".image-lightbox img").boundingBox();
    const overlay = await page.locator(".image-lightbox__lettering").boundingBox();
    assert.deepEqual(overlay, image, "文字层必须与原图边界完全重合");
    await page.getByRole("button", { name: "适合窗口", exact: true }).click();
  }
  await page.setViewportSize({ width: 1440, height: 1000 });
  const candidateSrc = await page.locator(".image-lightbox img").getAttribute("src");
  await page.keyboard.press("ArrowRight");
  await page.waitForFunction(src => document.querySelector(".image-lightbox img")?.getAttribute("src") !== src, candidateSrc);
  await page.keyboard.press("ArrowLeft");
  await page.waitForFunction(src => document.querySelector(".image-lightbox img")?.getAttribute("src") === src, candidateSrc);
  await page.keyboard.press("Escape");
  await page.screenshot({ path: fileURLToPath(new URL("../../runtime/finished-editor-ui.png", import.meta.url)) });
  await page.reload();
  await page.getByRole("button", { name: "输出", exact: true }).click();
  await page.getByRole("button", { name: "成品", exact: true }).click();
  await page.getByRole("button", { name: "导出", exact: true }).click();
  const download = page.waitForEvent("download");
  await page.getByRole("button", { name: "导出图片 ZIP", exact: true }).click();
  assert.match((await download).suggestedFilename(), /成品.zip$/);
  await page.getByRole("button", { name: "导出", exact: true }).click();
  await page.getByRole("radio", { name: "轻量 HTML", exact: true }).check();
  const htmlDownload = page.waitForEvent("download");
  await page.getByRole("button", { name: "导出预览 HTML", exact: true }).click();
  const offline = await browser.newPage({ viewport: { width: 900, height: 1000 } });
  await offline.context().setOffline(true);
  await offline.setContent(await readFile(await (await htmlDownload).path(), "utf8"));
  await offline.locator("img").evaluateAll(images => Promise.all(images.map(img => img.decode())));
  assert.equal(await offline.locator("img").count(), 2);
  await offline.getByRole("button", { name: "水平", exact: true }).click();
  await offline.locator(".finished-reader").hover();
  await offline.mouse.wheel(0, 900);
  await offline.getByLabel("当前页码").filter({ hasText: /^2$/ }).waitFor();
  await offline.getByRole("button", { name: "垂直", exact: true }).click();
  assert.ok(await offline.locator(".finished-reader").evaluate(element => element.scrollTop > 0));
  await offline.close();
  await page.setViewportSize({ width: 390, height: 844 });
  assert.ok(await page.locator(".finished-toolbar").evaluate(element => element.getBoundingClientRect().right <= innerWidth), "手机工具栏不横向溢出");
  await page.screenshot({ path: fileURLToPath(new URL("../../runtime/finished-mobile-ui.png", import.meta.url)) });
  await page.setViewportSize({ width: 1440, height: 1000 });
  for (const point of [{ x: 420, y: 410 }, { x: 670, y: 520 }, { x: 1430, y: 990 }]) {
    await page.locator(".finished-image").first().evaluate((element, point) => element.dispatchEvent(new MouseEvent("contextmenu", { bubbles: true, clientX: point.x, clientY: point.y })), point);
    const menu = page.getByRole("menu", { name: "成品 001" });
    await menu.waitFor();
    const bounds = await menu.boundingBox();
    assert.ok(Math.abs(bounds.x - Math.max(8, Math.min(point.x, 1440 - bounds.width - 8))) <= 1, `菜单横坐标应跟随指针：${JSON.stringify(bounds)}`);
    assert.ok(Math.abs(bounds.y - Math.max(8, Math.min(point.y, 1000 - bounds.height - 8))) <= 1, `菜单纵坐标应跟随指针：${JSON.stringify(bounds)}`);
    await page.keyboard.press("Escape");
  }
  await page.locator(".finished-image").first().click({ button: "right" });
  await page.getByRole("menuitem", { name: "删除成品", exact: true }).click();
  await page.getByRole("dialog", { name: "删除成品 001" }).getByRole("button", { name: "删除成品", exact: true }).click();
  await page.locator(".finished-card").first().getByText("尚未制作", { exact: true }).first().waitFor();
  assert.equal(await page.locator(".finished-card").first().getByRole("heading").innerText(), "001");
  assert.equal(await page.locator(".finished-card").first().locator("img").count(), 0);
  assert.deepEqual(errors, []);
});
