import { mediaReview, mediaReviewHint } from './media-review.mjs';
import { endpoint, projectPath, encode, pageKey, localImage, downloadArtifact } from './http-action.mjs';
import { schema, string, array, object, boolean, pagination, paginate, invalid } from './contract.mjs';
const resourceKinds=['models','fonts','extensions','workflows','render_profiles','visual_page_templates','dictionaries'];
const kind={...string('资源分类'),enum:resourceKinds};
function items(value,kind){const found=value[kind];return Array.isArray(found)?found:found?.items??found?.templates??[];}
export const managementActions={
  'story.context':endpoint('读取当前故事骨架与指定单元上下文','POST','/api/agent/story-context',{project_id:string('项目ID'),sequence_id:string('可选单元ID')},{required:['project_id'],body:a=>a,details:'按需读取故事上下文；不是可写草稿；梗概用 story.synopsis.read/save，章节和单元标题、梗概用 chapter.read/save 或 sequence.read/save。'}),
  'resource.list':endpoint('分页查询基模、字体、工作流等资源','GET','/api/resources',{kind,...pagination},{required:['kind'],transform:(r,a)=>paginate(items(r.value,a.kind).map(item=>typeof item==='string'?{id:item,name:item}:({id:item.id??item.relative_path??item.name,name:item.name,relative_path:item.relative_path,status:item.status,available:item.available})),a),details:'kind 选择资源类别；只返回摘要。详情用 resource.inspect。工作台不提供资源文件编辑接口，安装与更新 ComfyUI 用 runtime 操作。'}),
  'resource.inspect':endpoint('读取一项资源的完整详情','GET','/api/resources',{kind,id:string('resource.list 返回的 ID')},{transform:(r,a)=>{const item=items(r.value,a.kind).find(v=>(typeof v==='string'?v:v.id??v.relative_path??v.name)===a.id);if(!item)throw invalid('资源不存在');return item;}}),
  'resource.lora.image':{summary:'下载 LoRA 资源的预览或示例图',parameters:schema({resource_id:string('已登记资源 ID'),file:string('resource.lora.inspect 中 previews/examples 的 file')}),details:'仅读取现有图片，返回本地文件供 read_image 查看。',execute:a=>downloadArtifact(`/api/lora-resources/${encode(a.resource_id)}/media/${a.file.split('/').map(encode).join('/')}`)},
  'runtime.hardware':endpoint('查询硬件和 ComfyUI 状态','GET','/api/hardware-status'),
  'runtime.refresh':endpoint('刷新生成环境连接','POST','/api/comfyui/refresh'),
  'runtime.select':endpoint('选择已登记 ComfyUI 地址','POST','/api/comfyui/select',{url:string('runtime.hardware 返回的可用地址')},{body:a=>a}),
  'runtime.install':endpoint('安装配置中的 ComfyUI 环境','POST','/api/comfyui/install',{device:{...string('设备类型'),enum:['nvidia','amd','m-series','cpu']}},{body:a=>a,details:'仅在用户授权安装时执行；可能下载大量依赖。不会自动启动生成或训练。'}),
  'runtime.update':endpoint('更新配置中的 ComfyUI','POST','/api/comfyui/update',{}, {details:'须用户授权更新；不自动生成图片。'}),
  'runtime.start':endpoint('启动 ComfyUI 服务','POST','/api/comfyui/start',{}, {details:'只启动服务，不提交模型任务。'}),
  'runtime.stop':endpoint('停止 ComfyUI 服务','POST','/api/comfyui/stop',{}, {details:'会影响正在运行的生成；须用户授权停止。'}),
  'project.rename':endpoint('重命名项目目录与登记 ID','POST',a=>projectPath(a,'rename'),{id:string('新项目 ID')},{project:true,credential:'revision',body:a=>({id:a.id}),details:'先 project.settings.read 获取 revision；改变目录与登记身份，不只修改标题。'}),
  'project.migration.read':endpoint('查询项目模型格式迁移计划','GET',a=>projectPath(a,'model-migration'),{}, {project:true}),
  'project.migration.apply':endpoint('按已检查计划执行模型格式迁移','POST',a=>projectPath(a,'model-migration'),{fingerprint:string('migration.read 返回的 fingerprint')},{project:true,credential:'revision',body:a=>({fingerprint:a.fingerprint}),details:'读取计划后确认范围，携带同次读取 revision 和 fingerprint；变化拒绝。'}),
  'task.cancel':endpoint('取消已有生成或成品任务','POST',a=>`/api/tasks/${encode(a.project_id)}/${encode(a.task_id)}/control`,{project_id:string('任务项目ID；comparison可使用 _'),task_id:string('任务ID'),purpose:{...string('类型'),enum:['candidate','comparison','finished']}},{required:['project_id','task_id'],body:a=>({action:'cancel',purpose:a.purpose??'candidate'}),details:'purpose 默认 candidate；只取消，不启动模型；用 task.wait 等待终态。'}),
  'task.reorder':endpoint('调整等待队列顺序','POST','/api/tasks/reorder',{items:array('task.list 返回的队列引用 {project_id,task_id,purpose}',object('队列引用')),expected_revision:{type:'integer',description:'队列 revision，不是项目 revision'}},{body:a=>a,details:'必须传全部待排序引用，保持身份；陈旧队列版本拒绝。'}),
  'task.results':endpoint('查询任务已有结果图片','GET',a=>`/api/tasks/${encode(a.project_id)}/${encode(a.task_id)}/results`,{project_id:string('项目ID，全局comparison使用 _'),task_id:string('任务ID'),...pagination,purpose:{...string('类型'),enum:['candidate','comparison','finished']}},{required:['project_id','task_id'],query:a=>({purpose:a.purpose??'candidate'}),transform:(r,a)=>({...paginate(r.value.images.map(mediaReview),a),read_with:mediaReviewHint}),details:'只返回指定任务仍存在的已完成图片，含绝对路径；默认20条，最多50条。next_offset 非空时继续查询本操作，不扫描 Outputs。purpose 默认 candidate；全局 comparison 的 project_id 使用 _。'}),
  'page.text-source.delete':endpoint('删除单条引用语料','DELETE',a=>projectPath(a,`workbench/page-text-sources/${encode(a.page_key.page_id)}`),{page_key:pageKey,dialogue_id:string('要移除语料的文案ID'),expected_sha256:string('facts.read page/text-sources 返回的指纹'),expected_context_sha256:string('同次读取的上游指纹')},{project:true,body:a=>({dialogue_id:a.dialogue_id,expected_sha256:a.expected_sha256,expected_context_sha256:a.expected_context_sha256}),details:'先 facts.read page/text-sources，只移除指定文案的语料引用，不删除文案本身。'}),
  'page.prompt.import':endpoint('将页面 Anima Prompt 重新导入 Qwen 分支','POST',a=>projectPath(a,'workbench/qwen-import'),{page_key:pageKey,expected_prompt_sha256:string('facts.read page/prompt 返回的 expected_sha256'),expected_render_sha256:string('facts.read page/render 返回的 expected_sha256')},{project:true,body:a=>({page_key:a.page_key,expected_prompt_sha256:a.expected_prompt_sha256,expected_render_sha256:a.expected_render_sha256}),details:'页面当前模型必须为 qwen，并已存在两个模型分支；覆盖 Qwen 的本页文本但不运行模型。先确认用户编辑范围。'}),
  'corpus.context':endpoint('读取语料命中位置的前后文','GET',a=>projectPath(a,'workbench/text-source-context'),{source_file:string('语料来源文件'),offset:{type:'integer',minimum:0,description:'命中偏移'}},{project:true,query:a=>({source_file:a.source_file,offset:a.offset})}),
  'material.import':endpoint('将本机图片导入项目材料','PUT',a=>projectPath(a,'materials/item'),{file:string('本机图片绝对路径'),name:string('保存到材料目录的文件名，包含扩展名'),title:string('标题')},{project:true,credential:'revision',body:async a=>({file:a.name,title:a.title,encoding:'base64',content:(await localImage(a.file)).content}),details:'以原图内容保存，不加载模型。revision 来自 project.settings.read；参考图引用另用 reference.save。'}),
};
