import {endpoint,projectPath} from './http-action.mjs';
import {schema,string,object,array} from './contract.mjs';
const pageKey=schema({page_id:string('页面 ID')},['page_id']);
const locale={...string('目标语言'),enum:['en','ja']};
export const translationActions={
  'translation.inspect':endpoint('用实际浏览器排版检查译文，并保存预览图','POST',a=>projectPath(a,'workbench/translation/inspect'),{page_key:pageKey,locale,candidate_id:string('插画页：显式预览候选 ID；与 clean_locale 二选一'),clean_locale:{...string('插画页：显式使用哪种语言成品的无字底图；不会超分'),enum:['zh','en','ja']}},{project:true,required:['page_key','locale'],body:a=>({page_key:a.page_key,locale:a.locale,candidate_id:a.candidate_id,clean_locale:a.clean_locale}),transform:r=>r.value,details:'文字页无需底图。只读已保存事实，不生成译文、不超分、不制作成品；返回 preview_file、归一化实际框体、blockers、warnings。缺译和原文变化通过 translation_summary 返回；超出中文占用预算只告警，实际裁切阻止输出。Agent 可按建议缩短译文，通常最多两次；之后直接报告限制。'}),
  'translation.read':endpoint('读取中文嵌字、目标译文及写入指纹','POST',a=>projectPath(a,'workbench/translation/read'),{page_key:pageKey,locale},{project:true,body:a=>({page_key:a.page_key,locale:a.locale}),transform:r=>r.value,details:'只翻译嵌字和文字页展示标题、正文；不翻译 Prompt 或图片内文字。按 lines 的稳定 ID 写回。缺译为空；stale 表示原文已变化。英文简短自然，日文横排；尽量接近中文占用空间。可由人类手写或当前 DSH 会话翻译，不启动模型。'}),
  'translation.save':endpoint('合并保存一个语言分支的译文','POST',a=>projectPath(a,'workbench/translation/save'),{page_key:pageKey,locale,entries:object('稳定 ID 到译文字符串的映射；null 或空串删除；只写需要修改的条目'),expected_source_sha256:string('read 返回的原文范围指纹'),expected_translation_sha256:string('read 返回的本语言分支指纹')},{project:true,body:a=>({page_key:a.page_key,locale:a.locale,entries:a.entries,expected_source_sha256:a.expected_source_sha256,expected_translation_sha256:a.expected_translation_sha256}),transform:r=>r.value,details:'不覆盖另一语言。未写入的条目保留原文指纹；显式重写相同译文会确认当前原文。409 时重新读取并判断冲突。译文不会改动中文或布局。'}),
};
translationActions['translation.batch.read']={summary:'读取最多16页的目标语言嵌字',parameters:schema({project_id:string('项目 ID'),locale,page_keys:array('明确的页面身份',pageKey,16)},['project_id','locale','page_keys']),details:'返回逐页结果，中文和译文按稳定 ID 对齐；结合当前会话故事上下文直接翻译，不调用新的模型服务。',execute:async args=>({pages:await Promise.all(args.page_keys.map(page_key=>translationActions['translation.read'].execute({project_id:args.project_id,locale:args.locale,page_key})) )})};
translationActions['translation.batch.save']={summary:'逐页保存最多16页的译文，返回独立成败',parameters:schema({project_id:string('项目 ID'),locale,pages:array('每页的 page_key、entries 和两个 read 指纹',object(),16)},['project_id','locale','pages']),details:'每页独立提交；成功页不重放，失败页保留旧事实并报告原因。',execute:async args=>{const pages=[];for(const page of args.pages){try{pages.push({page_key:page.page_key,ok:true,value:await translationActions['translation.save'].execute({...page,project_id:args.project_id,locale:args.locale})});}catch(error){pages.push({page_key:page.page_key,ok:false,error:error.message});}}return {pages};}};
