import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { migrateUnifiedPages } from '../server/unified-pages-migration.mjs';

const save = async (root, file, value) => { const target = path.join(root, file); await mkdir(path.dirname(target), { recursive: true }); await writeFile(target, typeof value === 'string' ? value : JSON.stringify(value)); };
const json = async (root, file) => JSON.parse(await readFile(path.join(root, file), 'utf8'));

test('一次性迁移保留角色显式引用、场景继承调整和冻结证据，处理页面 ID 冲突', async context => {
  const root = await mkdtemp(path.join(tmpdir(), 'unified-migration-'));
  context.after(() => rm(root, { recursive: true, force: true }));
  const directory = path.join(root, 'workspace', 'example');
  const categories = { subject: [], person: [], setting: [], camera: [], avoid: [] };
  await save(directory, 'story/pages/index.json', { by_sequence: { opening: ['page-001'] } });
  await save(directory, 'characters/pages/index.json', { pages: [{ page_id: 'page-001', character_id: 'alice', variant_id: 'default' }] });
  await save(directory, 'story/pages/page-001.narrative.json', { title: '开场', scene_description: '车站', characters: [], dialogue: [] });
  await save(directory, 'characters/pages/page-001.goal.json', { title: '站姿' });
  const prompt = { ...categories, scene_id: 'station', inheritance: { 'scene:station': { night: { enabled: false } } } };
  await save(directory, 'story/pages/page-001.prompt.json', prompt);
  await save(directory, 'characters/pages/page-001.prompt.json', prompt);
  await save(directory, 'scenes.json', { scenes: [{ id: 'station', name: '车站', prompt: { ...categories, setting: [{ tag: 'night' }] } }] });
  const candidate = 'candidate-11111111-1111-4111-8111-111111111111';
  const media = `Outputs/characters/alice/page-001/${candidate}`;
  await save(directory, `${media}/image.png`, 'image-byte-fixture');
  await save(directory, `${media}/generation.json`, '{"frozen":"unchanged", "page_key":{"owner_kind":"character","owner_id":"alice","page_id":"page-001"}}\n');
  await save(directory, `${media}/result.json`, { page_key: { owner_kind: 'character', owner_id: 'alice', page_id: 'page-001' }, file: `${media}/image.png` });
  const taskPath = 'Saved/render/history/render-20260828T010203Z-1234abcd';
  const frozenManifest = '{\"frozen\":true}\n';
  await save(directory, `${taskPath}/manifest.json`, frozenManifest);
  await save(directory, `${taskPath}/state.json`, { status: 'completed', pages: [{ page_key: { owner_kind: 'character', owner_id: 'alice', page_id: 'page-001' } }], items: [{ page_key: { owner_kind: 'character', owner_id: 'alice', page_id: 'page-001' }, file: `${media}/image.png` }] });
  const before = await readFile(path.join(directory, `${media}/generation.json`));
  const preview = await migrateUnifiedPages(directory);
  assert.equal(preview.pages, 2);
  assert.equal(preview.renamed.length, 1);
  await assert.rejects(readFile(path.join(directory, 'pages/index.json')), { code: 'ENOENT' });
  const result = await migrateUnifiedPages(directory, { apply: true, backupDirectory: path.join(root, 'backup') });
  const index = await json(directory, 'pages/index.json');
  const characterPage = index.pages.find(page => page.owner_kind === 'character');
  assert.notEqual(characterPage.page_id, 'page-001');
  const content = await json(directory, `pages/${characterPage.page_id}.content.json`);
  assert.deepEqual(content.characters, [{ character_id: 'alice', variant_id: 'default' }]);
  assert.equal(content.scene_description, '');
  const migratedPrompt = await json(directory, `pages/${characterPage.page_id}.prompt.json`);
  assert.deepEqual(migratedPrompt.inheritance, { 'scene:station:default': { night: { enabled: false } } });
  assert.equal(migratedPrompt.scene_variant_id, 'default');
  const destination = `Outputs/pages/${characterPage.page_id}/${candidate}`;
  assert.deepEqual(await readFile(path.join(directory, `${destination}/generation.json`)), before);
  assert.equal(await readFile(path.join(directory, `${destination}/image.png`), 'utf8'), 'image-byte-fixture');
  assert.deepEqual((await json(directory, `${destination}/result.json`)).page_key, { page_id: characterPage.page_id });
  assert.equal((await json(directory, `${destination}/result.json`)).file, `${destination}/image.png`);
  assert.deepEqual((await json(directory, 'scenes/station.prompt.json')).identity.prompt.setting, [{ tag: 'night' }]);
  const state = await json(directory, `${taskPath}/state.json`);
  assert.deepEqual(state.pages[0].page_key, { page_id: characterPage.page_id });
  assert.deepEqual(state.items[0].page_key, { page_id: characterPage.page_id });
  assert.equal(state.items[0].file, `${destination}/image.png`);
  assert.equal(await readFile(path.join(directory, `${taskPath}/manifest.json`), 'utf8'), frozenManifest);
  assert.equal(result.backup, path.join(root, 'backup'));
  assert.deepEqual(await migrateUnifiedPages(directory, { apply: true }), { migrated: false, reason: 'already_current' });
});

test('预演拒绝缺失事实且不写入，未完成迁移要求先恢复备份', async context => {
  const root = await mkdtemp(path.join(tmpdir(), 'unified-preflight-'));
  context.after(() => rm(root, { recursive: true, force: true }));
  await save(root, 'story/pages/index.json', { by_sequence: { opening: ['page-001'] } });
  await assert.rejects(migrateUnifiedPages(root), /页面内容缺失/);
  await assert.rejects(readFile(path.join(root, 'pages/index.json')), { code: 'ENOENT' });
  await save(root, '.storage-migration.json', { backup: 'previous-backup' });
  await assert.rejects(migrateUnifiedPages(root, { apply: true }), /previous-backup/);
});
