import { inspectPageRender } from '../server/page-render-inspection.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,cp,rm} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import sharp from 'sharp';
import Ajv from 'ajv/dist/2020.js';
import {registerFixtureProjects} from './project-registry-fixture.mjs';
import {createPage} from '../server/page-facts.mjs';
import {readReferenceLibrary,mutateReferenceLibrary} from '../server/reference-library.mjs';
import {readFactDraft,saveFactDraft} from '../server/fact-drafts.mjs';
import {compileAndPersistWorkbenchRenderTask} from '../server/page-render.mjs';
import {videoTiming} from '../server/models/h3/prompt.mjs';
import {validateFrozenRenderTask} from '../server/render-task-contract.mjs';
import {readVideoSource} from '../server/video-source.mjs';
import {finishedReaderDocument} from '../shared/finished-reader.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const schema=name=>`https://storyvisualizer.local/schemas/${name}.schema.json`;
test('H3 时长按原生帧网格转换，拒绝越界或非数值',()=>{
  assert.deepEqual([3,5,8,10].map(s=>videoTiming(s).frames),[73,124,192,243]);
  for(const s of [2,16,NaN,'5'])assert.throws(()=>videoTiming(s));
});
test('动态页创建、来源推荐、中文输入、单视频冻结和循环拓扑',async t=>{
  await mkdir(path.join(root,'Saved/Tests'),{recursive:true});const base=await mkdtemp(path.join(root,'Saved/Tests/video-'));t.after(()=>rm(base,{recursive:true,force:true}));
  const directory=path.join(base,'workspace/demo');
  const put=async(f,v)=>{await mkdir(path.dirname(path.join(directory,f)),{recursive:true});await writeFile(path.join(directory,f),JSON.stringify(v));};
  for(const folder of ['render-profiles','render-recipes','workflows','prompt-policies'])await cp(path.join(root,'library',folder),path.join(base,'library',folder),{recursive:true});
  await put('project.json',{format:'story-models-v1',title:'动态测试',canvas:'3:4',default_render_profile:'anima-base-v1'});
  await put('story/outline.json',{$schema:schema('story-outline'),synopsis:'测试',chapters:[{id:'main',title:'章',summary:'测试',sequences:[{id:'one',title:'单元',summary:'测试'}]}]});
  await put('pages/index.json',{$schema:schema('pages-index'),pages:[]});
  await put('characters/index.json',{$schema:schema('character-index'),characters:[]});
  await put('scenes/index.json',{$schema:schema('scene-index'),scenes:[]});registerFixtureProjects(base);
  const owner={owner_kind:'story',sequence_id:'one'};
  const illustration=await createPage(base,'demo',owner);
  await createPage(base,'demo',owner,{pageKind:'text'});
  const video=await createPage(base,'demo',owner,{pageKind:'video'});
  const lookup=await readVideoSource(base,'demo',directory,{page_key:video.page_key});assert.deepEqual(lookup.source_page_key,illustration.page_key);assert.deepEqual(lookup.candidates,[]);
  const target={kind:'page',id:video.page_id};
  const bytes=await sharp({create:{width:384,height:512,channels:3,background:'blue'}}).png().toBuffer();
  const refs=await readReferenceLibrary(base,'demo',target);
  await mutateReferenceLibrary(base,directory,'demo',{target,action:'save',expected_sha256:refs.sha256,content:bytes.toString('base64')});
  const args={projectId:'demo',domain:'page',kind:'prompt',targetId:video.page_id};const draft=await readFactDraft(base,args);
  draft.document.models.h3={...draft.document.models.h3,text:'女子走过门口，镜头固定。',duration:3,quality:'preview',steps:12};
  await saveFactDraft(base,{...args,document:draft.document,expectedSha256:draft.expected_sha256,expectedContextSha256:draft.expected_context_sha256});
  const compile=()=>compileAndPersistWorkbenchRenderTask(base,'demo',{page_key:video.page_key});
  const ordinary=await compile();assert.equal(ordinary.task.items.length,1);validateFrozenRenderTask(ordinary.task);
  const inspection=await inspectPageRender({repositoryRoot:base,projectDirectory:directory,pageKey:video.page_key});
  const api=ordinary.task.snapshot.execution_units[0].workflow.api;
  assert.equal(api['1'].inputs.unet_name,'minimax_h3_fl2va_pruned_int8_convrot.safetensors');
  assert.equal(Object.values(api).some(node=>node.class_type==='LoraLoaderModelOnly'),false);
  assert.deepEqual(api['7'].inputs.model,['1',0]);
  assert.deepEqual(api['10'].inputs.model,['1',0]);
  assert.deepEqual(ordinary.task.items[0].loras,[]);
  assert.deepEqual(inspection.loras,[]);
  assert.deepEqual(inspection.execution_parameters.dimensions,{width:api['6'].inputs.width,height:api['6'].inputs.height});
  assert.equal(inspection.execution_parameters.steps,api['10'].inputs.steps);
  assert.equal(inspection.execution_parameters.video.frames,api['6'].inputs.length);
  assert.deepEqual(inspection.generation.parameters.dimensions,inspection.execution_parameters.dimensions);
  assert.equal(api['6'].inputs.length,73);assert.equal(api['10'].inputs.steps,12);assert.equal(api['6'].inputs.last_frame,undefined);
  assert.equal(api['6'].inputs.width,576);assert.equal(api['6'].inputs.height,768);assert.equal(api['14'].inputs.fps,24);
  assert.match(api['6'].inputs.prompt,/女子走过门口/);assert.ok(api['6'].inputs.prompt.includes('\n\n'));assert.equal(api['14'].inputs.audio,undefined);
  const altered=structuredClone(ordinary.task);altered.items[0].video_settings.fps=12;assert.throws(()=>validateFrozenRenderTask(altered));
  const loop=await readFactDraft(base,args);loop.document.models.h3.loop=true;
  await saveFactDraft(base,{...args,document:loop.document,expectedSha256:loop.expected_sha256,expectedContextSha256:loop.expected_context_sha256});
  const loopTask=await compile();assert.deepEqual(loopTask.task.snapshot.execution_units[0].workflow.api['6'].inputs.last_frame,['5',0]);assert.equal(ordinary.task.items[0].video_settings.loop,false);
  const definition=JSON.parse(await readFile(path.join(root,'library/schemas/story-page-prompt.schema.json'),'utf8'));const validate=new Ajv({strict:false}).compile(definition);assert.equal(validate(loop.document),true,JSON.stringify(validate.errors));
});
test('混排阅读器为动态页生成可播放 MP4，保持普通页与顺序',()=>{
  const html=finishedReaderDocument([{src:'/a.png',number:1,width:768,height:1024},{src:'/clip.mp4',number:2,width:576,height:768,media_kind:'video'}]);
  assert.match(html,/<img loading="lazy" src="\/a.png"/);assert.match(html,/<video controls muted loop playsinline/);assert.ok(html.indexOf('/a.png')<html.indexOf('/clip.mp4'));
});
